### ISSUE TITLE
SSOWAT crash when it gets a request without a referer

### ISSUE THREAD

**Issue by Psycojoker** [Kloadut/SSOwat#54] opened 2016-03-07 10:10 UTC
On harpo cube:

```
2016/03/07 11:01:14 [error] 828#0: *19 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:41: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'sub'
        /usr/share/ssowat/helpers.lua:41: in function 'starts'
        /usr/share/ssowat/access.lua:133: in function </usr/share/ssowat/access.lua:1>, client: 10.0.242.247, server: harpo.nohost.me, request: "POST /yunohost/sso/?r=aHR0cDovL2hhcnBvLm5vaG9zdC5tZS8= HTTP/1.1", host: "harpo.nohost.me"
```

According to the stack trace this is the incriminated line: https://github.com/Kloadut/SSOwat/blob/1bceee6d6483440eb24a299e8c2cfe01ada57eff/access.lua#L133

A check if missing for when there is no referer, but then I don't know which behavior we should expect.

**Comment by Psycojoker** [comment] 2016-03-07 10:21
`network.http.sendRefererHeader` was set at `0` instead of `2` in `about:config` for wathever reason. This is still a strange behavior.

**Comment by Psycojoker** [comment] 2016-03-07 10:23
My best guest for now is a modification of the settings by `request policy` https://www.requestpolicy.com/ (and not invalidating those modifications when the plugin has been desactivated)

**Comment by Psycojoker** [comment] 2016-03-07 10:23
well, I find not mention of that in their source code https://github.com/RequestPolicy/requestpolicy/search?utf8=%E2%9C%93&q=sendRefererHeader+

**Comment by opi** [comment] 2016-03-07 10:55
Duplicate of https://github.com/Kloadut/SSOwat/issues/48 , and migrated to the YunoHost bugtracker as [dev.#79](https://dev.yunohost.org/issues/79).

**Closed** 2016-03-07 10:55 UTC
