### ISSUE TITLE
Usernames are only partially case-sensitive (500 internal server error)

### ISSUE THREAD

**Issue by daveross** [Kloadut/SSOwat#20] opened 2014-07-28 12:05 UTC
My username is "dave", which my iPad helpfully autocorrects to "Dave". This apparently gets past an initial check for valid credentials, but then I get a 500 error on every page load until I restart nginx and log in with the correct capitalization.

This might be a duplicate of #17 

2014/07/28 13:54:24 [error] 22849#0: *8 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:413: bad argument #1 to 'pairs' (
table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/share/ssowat/access.lua:413: in function 'get_data_for'
        /usr/share/ssowat/access.lua:359: in function </usr/share/ssowat/access.lua:308>
        (tail call): ?, client: 50.177.28.168, server: example.com, request: "GET /yunohost/sso/ HTTP/1.1", host: "example.com"

**Comment by opi** [comment] 2016-04-30 09:46
can't reproduce; In my case LDAP/YunoHost allow me to log regardless of my username case, without any errors.
This behavior is fine imho, I'll close this issue because it's triage & cleanup time ;)  
Feel free to reopen it if needed.

**Closed by opi** 2016-04-30 09:46 UTC
